# Generated by Django 4.0.5 on 2022-06-21 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro_livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('sub_titulo', models.CharField(max_length=200)),
                ('ISBN_10', models.IntegerField()),
                ('ISBN_13', models.IntegerField()),
                ('edicao', models.IntegerField()),
                ('editora', models.CharField(max_length=200)),
                ('ano', models.IntegerField()),
                ('paginas', models.IntegerField()),
                ('idioma', models.CharField(choices=[('PT-BR', 'Português do Brasil'), ('PT-PT', 'Português de Portugal'), ('EN', 'Inglês'), ('ES', 'Espanhol')], max_length=20)),
                ('sinopse', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cadastro_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=16)),
                ('nascimento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro/Prefiro não informar')], max_length=9)),
            ],
        ),
    ]
